// ============================================================================
// SENTINEL INVESTIGATION REPORT
// AI-generated natural language explanation with typewriter effect
// ============================================================================

"use client";

import { useState, useEffect, useRef } from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import { 
  Brain, 
  FileText, 
  Clock, 
  CheckCircle, 
  AlertTriangle,
  Copy,
  Check,
  RefreshCw,
  Sparkles
} from "lucide-react";

interface InvestigationReportProps {
  txnId: string;
  report?: string;
  isGenerating?: boolean;
  onRegenerate?: () => void;
  className?: string;
}

// Mock report for demonstration
const generateMockReport = (txnId: string): string => {
  return `## Transaction Analysis Report

### Executive Summary
Transaction **${txnId}** has been flagged as **HIGH RISK** with a confidence score of 94%. The ML ensemble model detected multiple anomaly indicators consistent with an **Account Takeover (ATO)** attack pattern.

### Key Findings

1. **Geographic Anomaly Detected**
   - Transaction originated from Lagos, Nigeria
   - User's historical transactions are 98% US-based
   - No prior activity from this region in 24 months

2. **Device Fingerprint Mismatch**
   - New device ID detected: \`DEV-NEW-X892\`
   - Device does not match any in user's trusted device list
   - Browser fingerprint indicates potential automation tools

3. **Behavioral Deviation**
   - Transaction amount ($15,420) is 847% above user's average
   - Purchase category (Electronics) differs from typical spending
   - Transaction time (03:22 AM local) is outside normal activity window

4. **Velocity Indicators**
   - 3 failed login attempts preceded this transaction
   - Password was reset 47 minutes before purchase
   - Multiple high-value transactions attempted within 10 minutes

### Recommended Actions
- **IMMEDIATE**: Block transaction and freeze account
- **SHORT-TERM**: Initiate customer verification via registered phone
- **LONG-TERM**: Flag account for enhanced monitoring (90 days)

### Model Confidence
The fraud detection ensemble achieved **94% confidence** on this classification:
- XGBoost: 92%
- Neural Network: 95%
- Graph Model: 96%

---
*Report generated by SENTINEL AI • Model v2.4.1 • Processing time: 847ms*`;
};

export function InvestigationReport({
  txnId,
  report,
  isGenerating = false,
  onRegenerate,
  className,
}: InvestigationReportProps) {
  const [displayedText, setDisplayedText] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [copied, setCopied] = useState(false);
  const [currentTime, setCurrentTime] = useState<string>("--:--:--");
  const fullReport = report || generateMockReport(txnId);
  const typingRef = useRef<NodeJS.Timeout | null>(null);

  // Client-side time
  useEffect(() => {
    setCurrentTime(new Date().toLocaleTimeString());
  }, []);

  // Typewriter effect
  useEffect(() => {
    if (isGenerating) {
      setDisplayedText("");
      setIsTyping(true);
      let index = 0;

      const typeNextChar = () => {
        if (index < fullReport.length) {
          setDisplayedText(fullReport.slice(0, index + 1));
          index++;
          // Variable typing speed for realism
          const delay = fullReport[index - 1] === "\n" ? 50 : Math.random() * 15 + 5;
          typingRef.current = setTimeout(typeNextChar, delay);
        } else {
          setIsTyping(false);
        }
      };

      typingRef.current = setTimeout(typeNextChar, 500);

      return () => {
        if (typingRef.current) clearTimeout(typingRef.current);
      };
    } else {
      setDisplayedText(fullReport);
      setIsTyping(false);
    }
  }, [isGenerating, fullReport]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(fullReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Simple markdown-like rendering
  const renderMarkdown = (text: string) => {
    return text.split("\n").map((line, i) => {
      // Headers
      if (line.startsWith("### ")) {
        return (
          <h3 key={i} className="text-[#38bdf8] font-semibold text-sm mt-4 mb-2">
            {line.replace("### ", "")}
          </h3>
        );
      }
      if (line.startsWith("## ")) {
        return (
          <h2 key={i} className="text-[#f0f4f8] font-bold text-base mt-5 mb-3 pb-2 border-b border-[rgba(148,163,184,0.1)]">
            {line.replace("## ", "")}
          </h2>
        );
      }
      // Bold text
      if (line.includes("**")) {
        const parts = line.split(/\*\*(.*?)\*\*/g);
        return (
          <p key={i} className="text-[#94a3b8] text-sm leading-relaxed my-1">
            {parts.map((part, j) =>
              j % 2 === 1 ? (
                <strong key={j} className="text-[#f0f4f8] font-semibold">
                  {part}
                </strong>
              ) : (
                part
              )
            )}
          </p>
        );
      }
      // Code blocks
      if (line.includes("`")) {
        const parts = line.split(/`(.*?)`/g);
        return (
          <p key={i} className="text-[#94a3b8] text-sm leading-relaxed my-1">
            {parts.map((part, j) =>
              j % 2 === 1 ? (
                <code key={j} className="px-1.5 py-0.5 bg-[#0f1419] rounded text-[#38bdf8] font-mono text-xs">
                  {part}
                </code>
              ) : (
                part
              )
            )}
          </p>
        );
      }
      // List items
      if (line.startsWith("- ")) {
        return (
          <div key={i} className="flex items-start gap-2 my-1 ml-2">
            <span className="text-[#38bdf8] mt-1">•</span>
            <span className="text-[#94a3b8] text-sm">{line.replace("- ", "")}</span>
          </div>
        );
      }
      // Numbered lists
      if (/^\d+\.\s/.test(line)) {
        const [num, ...rest] = line.split(". ");
        return (
          <div key={i} className="flex items-start gap-2 my-2">
            <span className="text-[#fbbf24] font-mono text-xs bg-[rgba(251,191,36,0.1)] px-1.5 py-0.5 rounded">
              {num}
            </span>
            <span className="text-[#f0f4f8] text-sm font-medium">{rest.join(". ")}</span>
          </div>
        );
      }
      // Horizontal rule
      if (line.startsWith("---")) {
        return <hr key={i} className="border-[rgba(148,163,184,0.1)] my-4" />;
      }
      // Italics (report footer)
      if (line.startsWith("*") && line.endsWith("*")) {
        return (
          <p key={i} className="text-[#64748b] text-xs italic mt-4">
            {line.replace(/^\*|\*$/g, "")}
          </p>
        );
      }
      // Empty lines
      if (line.trim() === "") {
        return <div key={i} className="h-2" />;
      }
      // Regular text
      return (
        <p key={i} className="text-[#94a3b8] text-sm leading-relaxed my-1">
          {line}
        </p>
      );
    });
  };

  return (
    <div className={cn("bg-[#151b23] border border-[rgba(148,163,184,0.08)] rounded-xl overflow-hidden", className)}>
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 bg-[#0f1419] border-b border-[rgba(148,163,184,0.08)]">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-[rgba(168,85,247,0.15)]">
            <Brain className="w-4 h-4 text-[#a855f7]" />
          </div>
          <div>
            <h3
              className="text-[14px] font-semibold text-[#f0f4f8]"
              style={{ fontFamily: "'Space Grotesk', sans-serif" }}
            >
              AI Investigation Report
            </h3>
            <p className="text-[10px] text-[#64748b] font-mono">
              Powered by Mistral-7B + SENTINEL Analysis Engine
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {isTyping && (
            <motion.div
              animate={{ opacity: [1, 0.5, 1] }}
              transition={{ duration: 1, repeat: Infinity }}
              className="flex items-center gap-1.5 px-2 py-1 bg-[rgba(168,85,247,0.15)] rounded-full"
            >
              <Sparkles className="w-3 h-3 text-[#a855f7]" />
              <span className="text-[10px] font-mono text-[#a855f7]">Generating...</span>
            </motion.div>
          )}
          <button
            onClick={handleCopy}
            className="p-2 rounded-lg hover:bg-[rgba(148,163,184,0.1)] text-[#64748b] hover:text-[#f0f4f8] transition-colors"
            title="Copy report"
          >
            {copied ? <Check className="w-4 h-4 text-[#34d399]" /> : <Copy className="w-4 h-4" />}
          </button>
          {onRegenerate && (
            <button
              onClick={onRegenerate}
              disabled={isTyping}
              className="p-2 rounded-lg hover:bg-[rgba(148,163,184,0.1)] text-[#64748b] hover:text-[#f0f4f8] transition-colors disabled:opacity-50"
              title="Regenerate report"
            >
              <RefreshCw className={cn("w-4 h-4", isTyping && "animate-spin")} />
            </button>
          )}
        </div>
      </div>

      {/* Report Content */}
      <div className="p-5 max-h-[500px] overflow-y-auto">
        {isGenerating && displayedText === "" ? (
          <div className="flex flex-col items-center justify-center py-12">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
            >
              <Brain className="w-8 h-8 text-[#a855f7]" />
            </motion.div>
            <p className="mt-4 text-sm font-mono text-[#64748b]">LOADING INTELLIGENCE...</p>
            <div className="mt-2 flex gap-1">
              {[0, 1, 2].map((i) => (
                <motion.div
                  key={i}
                  animate={{ opacity: [0.3, 1, 0.3] }}
                  transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                  className="w-2 h-2 bg-[#a855f7] rounded-full"
                />
              ))}
            </div>
          </div>
        ) : (
          <div className="prose prose-invert max-w-none">
            {renderMarkdown(displayedText)}
            {isTyping && (
              <motion.span
                animate={{ opacity: [1, 0] }}
                transition={{ duration: 0.5, repeat: Infinity }}
                className="inline-block w-2 h-4 bg-[#38bdf8] ml-0.5"
              />
            )}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between px-5 py-3 bg-[#0f1419] border-t border-[rgba(148,163,184,0.08)]">
        <div className="flex items-center gap-4 text-[10px] font-mono text-[#64748b]">
          <span className="flex items-center gap-1.5">
            <Clock className="w-3 h-3" />
            Generated: {currentTime}
          </span>
          <span className="flex items-center gap-1.5">
            <FileText className="w-3 h-3" />
            {fullReport.split(" ").length} words
          </span>
        </div>
        {!isTyping && displayedText.length > 0 && (
          <div className="flex items-center gap-1.5 text-[10px] font-mono text-[#34d399]">
            <CheckCircle className="w-3 h-3" />
            Report Complete
          </div>
        )}
      </div>
    </div>
  );
}

export default InvestigationReport;
